platform :ios
pod 'Reachability',  '~> 3.0.0'
pod 'SBJson', '~> 4.0.0'

platform :ios, '7.0'
pod 'AFNetworking', '~> 3.0'
pod 'OpenSSL', '~> 1.0'
pod 'GDataXML-HTML', '~> 1.1.0'
pod 'RDVTabBarController'
pod 'ODRefreshControl'
pod 'JazzHands', '2.0.0'
pod 'SMPageControl'
pod 'Masonry'
pod 'NYXImagesKit'